services:
  - type: web_service
    name: ingodspresence-backend
    env: docker
    plan: free
    repo: https://github.com/micciarellijayden123-tech/Ingodspresence
    branch: main
    rootDirectory: .
    dockerfilePath: Dockerfile
    envVars:
      - key: JWT_SECRET
        value: change_me_secret
      - key: ADMIN_USER
        value: Jayden Micciarelli
      - key: ADMIN_PASS
        value: 123456
      - key: PAYPAL_ENV
        value: sandbox
